### ISSUE TITLE
user-friendliness for bold words

### ISSUE THREAD

**Issue by sussman** [dhakajack/trfv#30]
Sometime in R0 after the user asks/tells about something for the first time, there's a hint about using shorthand to ask/tell.

HOWEVER, there's no hint at all the first time Christabell introduces herself and speaks bold words.  We need a hint that explains what the bold words mean the *first* time she says some.  (e.g. "you can ask or tell about bolded words to further the conversation."  

(This was confusing for Frances on first play.)

**Comment by dhakajack** [comment]
Great observation -- ok, hardwired into the first dialogue with bold.
