### ISSUE TITLE
N1 initial double description

### ISSUE THREAD

**Issue by sussman** [dhakajack/trfv#32]
Upon entering N1 for the first time, Frances saw three things in a row:

1.  (verbose room description) "You would have killed for a room like this..."
2.  (verbose tea party description)
3.  short descriptions of both room and tea party.

#3 is bizarre and redundant -- should only happen after a 'look' later on.

**Comment by dhakajack** [comment]
Room description was written with a "first/only" but should have put the two descriptions in a oneof/or/stopping construction
