### ISSUE TITLE
N1 missing topics

### ISSUE THREAD

**Issue by sussman** [dhakajack/trfv#33]
Asking about "tea" and "animals" gives a generic non-response from Carol.  But they're bolded subjects within the scene.

**Comment by sussman** [comment]
Aha, it appears that {tea, animals, snortles, elephant} are example of things that are bolded, can be *examined* but have no ask/tell response.  Confusing to Frances -- she expects bolded things to be askable.

**Comment by dhakajack** [comment]
No, bolded should be askable...investigating

**Comment by dhakajack** [comment]
The problem in both cases was that grammar was expressed using the slash notation, but included spaces. fixed.
